### ISSUE TITLE
Thumbnails disappear on browser resize...

### ISSUE THREAD

**Issue by chrispthomas1990** [bqworks/slider-pro#198] opened 2017-04-29 20:00 UTC
Hey,

I have been using the Slider Pro plugin for a client's site which is functioning exactly as they want it to, and just want to say what a great plugin this is!

This is only a minor issue, but, the thumbnails appear perfectly when you load the site on a desktop. Notice though, when you scale the browser window up and down, to test various mobile/tablet-style layouts, that the thumbnails disappear. That is until you click on one of the thumbnail navigation arrows, in which case they slide back in...

http://www.pratimakramer.co.uk/dev/

As I said this is only a minor issue, as whenever a user loads the site on their phone/tablet/computer it will be fine as long as they don't frantically scale the browser window :P. Does anyone know if there is a simple fix for this?

Thanks,

Chris

**Comment by davidghi** [comment] 2017-05-08 14:00
Hi, Chris. Yes, I can replicate it and I think I know what causes the problem. It will be fixed in the next update. Thank you for reporting it!

Cheers!

**Comment by chrispthomas1990** [comment] 2017-05-08 18:35
No problem. Thanks!

**Comment by exstocklet** [comment] 2019-04-19 00:22
I'm also having this problem, although the thumbnails don't disappear so much as they split into multiple rows.  Like the previous poster, it happens when the browser is resized, but for me it also happens when a mobile device changes orientation. 

Is a fix still to come?  If not, is there anything, even something hacky and inelegant, that I can do to make it pretend to be fixed?  Thanks!

**Comment by davidghi** [comment] 2019-04-19 09:48
Hi,

I'm not sure what were the issue and the fix for the previous poster. Can you post a link to your page, so I can take a look?

Best,
David

**Comment by exstocklet** [comment] 2019-04-19 20:44
Thanks for the quick response!  The previous issue was that thumbnails disappeared when the browser was resized after the page loaded, which is similar to (and possibly has the same cause as) my problem of the thumbnails separating into multiple rows.  You said (in May 2017) that you could replicate the previous poster's problem, and that it'd be fixed in the next update.

Here's my test site (note: only the residential section is active, but all pages within that section that have a gallery have the same problem):
http://studionexusarch.com/m-projects.html
At the moment, I've got it set to only display the first row of thumbnails, but that still means that some thumbnails disappear, and when they do, it's no longer possible to scroll to reveal the disappeared thumbnails.

**Comment by davidghi** [comment] 2019-04-20 18:08
Regarding the previous issue, I don't remember exactly how it behaved, where in the code was the problem and what was the fix. Anyway, in this case, the issue might also be due to using 'calc' instead of fixed values. You could try to use fixed values and use 'breakpoints' to change the size of the thumbnails based on screen size. If you don't want to use this method, I'll check if it's possible to fix with some additional CSS, but you should still try the fixed values to see if that is the cause of the problem.

Best,
David

**Comment by exstocklet** [comment] 2019-04-20 20:33
Thanks, I was coming to the conclusion that I'd have to give up the 'calc'--just haven't had the time to try it  yet. 

I hadn't thought of the 'breakpoints' at all, because frankly I don't understand them one bit, so I'll go learn about those and give it a shot.  Thanks so much for your help!

**Comment by davidghi** [comment] 2019-04-22 12:43
You're welcome! Breakpoints are similar to CSS media queries. They allow you to specify a set of settings that will be applied to the slider only if the screen is below a certain width. Examples 1 and 5 contain breakpoints.

Best,
David

**Comment by exstocklet** [comment] 2019-04-22 19:51
Nice!  Not only does this fix my current problem, it simplified a lot of other stuff, too.  Glad you included this option!

**Comment by davidghi** [comment] 2019-04-23 09:32
Glad I could help! :)

**Closed** 2021-07-22 13:03 UTC
